version: '3.8'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
      - client
    volumes:
      - static_volume:/usr/src/app/app/static    
  web:
    build:
      context:  ./services/web
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:5000 app:app
    volumes:
      - ./services/web:/usr/src/app
      - static_volume:/usr/src/app/app/static
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis      
  client:
    build:
      context: ./services/client
    volumes:
      - ./services/client/src:/usr/src/app/src
    expose:
      - 3000    
  db:
    image: postgres:12-alpine
    env_file:
      - ./.env.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  celery:
    build:
      context:  ./services/web
    command: "celery -A worker.celery_app worker --loglevel=info"
    user: nobody
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
  celery-beat:
    build:
      context:  ./services/web
    command: "celery -A worker.celery_app beat -S redbeat.RedBeatScheduler --loglevel=info --pidfile /tmp/celerybeat.pid -s /tmp/celerybeat-schedule"
    user: nobody
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: 'redis'
    volumes:
      - redis:/data      
volumes:
  postgres_data:
  redis:
  static_volume: